identifier: 6f161ffd172528918a4e
secret: bd70f1b10bdde095c0f501652422a3c877b2c85d

identifier_g: 545566810086-dn2v7n1uv1lc8knp22tmtv3n25q9dnd4.apps.googleusercontent.com
secret_g: S7Q2eLaMvi1fIngBtHBuMSTv

identifier_t: 284571835072542
secret_t: 2103ea3201832ced0ee6c488a0a2fc99